policy:
  - template: ["0-event-application-vetting.yml"]
    section:
      - id: ["eventtype"]
        block-list: []
        label:
          - name: "meetup-application"
            keys: ["Meetup"]
          - name: "wordcamp-application"
            keys: ["WordCamp"]
          - name: "wordpress-event-application"
            keys: ["WordPress Event"]
