name: New issue notifier

on:
  issues:
    types: [opened]

jobs:
  notify-coordinators:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v6
      with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Heads up @@WordPress/community-triage, we have a new issue open. Time to triage."
            })
  get-event-issue:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.issue.title , '[Meetup]')}}
    timeout-minutes: 30
    steps:
      - name: Add Comment
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Workflow running on: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}',
            });
        
      - uses: actions/github-script@v6
        name: Add label
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["environment/${{steps.inputs.outputs.dropdown_label}}"]
            });