name: "Event Application Vetting"
description: Add a Event Vetting Applications to track.
title: "[Event]: "
labels: ["event", "application", "Awaiting Triage"]
projects: ["WordPress/176"]
body:
  - type: "markdown"
    attributes:
      value: "Thanks for taking the time to fill out this Event Application!\n\n([Application Review](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/),  [Most Common Cases](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#most-common-cases-quick-step-by-step-guide), [Video tutorials](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#quick-step-by-step-video-tutorial-for-application-review))\n"
  - type: dropdown
    id: event_type
    attributes:
      label: Event Type
      description: Please select the applications event type below
      multiple: false
      options:
        - Meetup
        - WordCamp
        - WordPress Event
      default: 0
    validations:
      required: true
  - type: "input"
    id: event_name
    attributes:
      label: "Event Name"
      description: "Please provide the Event name (Meetup, WordCamp, WordPress Event)"
      placeholder: "<city>, <country>"
    validations:
      required: true
  - type: "input"
    id: event_tracker
    attributes:
      label: "Event Tracker URL"
      description: "Please provide the [WordCamp Central](https://central.wordcamp.org/) Event Tracker URL used for this application"
      placeholder: "https://central.wordcamp.org/"
    validations:
      required: true
