name: Issue labeler
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      issues: write

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3.1.0
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/0-event-application-vetting.yml
      - run: cat ${HOME}/issue-parser-result.json
      - run: echo $EVENTTYPE $EVENTNAME
        env:
          EVENTTYPE: ${{ steps.issue-parser.outputs.issueparser_eventtype }}
          EVENTNAME: ${{ steps.issue-parser.outputs.issueparser_eventname }}

      - name: Set labels based on Event Type field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v3.0.0
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: eventtype
          config-path: .github/label-policy.yml
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Event issue title
        uses: actions-cool/issues-helper@v3.6.0
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          state: "open"
          title: "[Event] ${{ steps.issue-parser.outputs.issueparser_eventtype }} ${{ github.event.issue.number }}"
          update-mode: "replace"
