name: Advanced Issue labeler
on:
  issues:
    types: [opened]

permissions:
  contents: read

jobs:
  label-component:
    runs-on: ubuntu-latest

    permissions:
      # required for all workflows
      issues: write

    steps:
      - uses: actions/checkout@v3

      - name: Parse issue form
        uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/0-event-application-vetting.yml
        env:
          EVENTJSON: ${{ steps.issue-parser.outputs.jsonString }}
          EVENTTYPE: ${{ steps.issue-parser.outputs.issue_parser.eventtype }}
          EVENTNAME: ${{ steps.issue-parser.outputs.issue_parser.eventname }}

      - name: Log Issue Value
        run: |
          echo "Issue Title: ${{ process.env.EVENTJSON }}"
          echo "Issue Body: ${{ github.event.issue.body }}"
          echo "Label: ${{ github.event.label.name }}"

      - name: Set labels based on Event Type field
        uses: redhat-plumbers-in-action/advanced-issue-labeler@v2
        with:
          issue-form: ${{ steps.issue-parser.outputs.jsonString }}
          section: eventtype
          block-list: |
            None
            Other
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Echo issue form as JSON String
        run: echo ${{ steps.issue-parser.outputs.jsonString }}

      - name: Update issue title
        uses: actions-cool/issues-helper@v3
        with:
          actions: "update-issue"
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          state: "open"
          title: "[Event] ${{ github.event.issue.number }}"
          update-mode: "replace"
          emoji: "+1"
