name: Close and label issue on publish comment

on:
  issue_comment:
    types: [created, edited]

jobs:
  publish-commment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '//publish')
    steps:
      - name: Change Labels
        shell: bash
        run: |
          gh issue edit -R "${{ github.repository }}" \
          "${{ github.event.issue.number }}" \
          --add-label "[Content] Published" \
          --remove-label "[Content] Needs Co-host"
          gh issue close -R "${{ github.repository }}" \
          --reason "completed" \
          "${{ github.event.issue.number }}"
        env:
          GH_TOKEN: ${{ github.token }}
