# This is a reusable workflow, called from other workflows
# See https://docs.github.com/en/actions/using-workflows/reusing-workflows

name: Comments on issues 
on:
  workflow_call:
    inputs:
      content-type:
        type: string

jobs:
  add-comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: peter-evans/create-or-update-comment@v3
        if: contains(inputs.content-type, 'meetup')  
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## Next steps

              - [ ] Please assign the issue to the team member and make sure to mark the issue ```To Do```
              - [ ] Assignee (Team Member) will mark the issue as ```In Progress``` and perform the vetting taks on the tracker and HS as indicated on the handbook
              - [ ] Once the vetting is completed mark the issue as ```In Review```

            ## Public vs Private

              - Use comments for questions about the process and changes or to indicate delays, holding situation.
              - Avoid discussing the community or the organiser in comments on Github. Even if there are doubts about some applications.
              - We do not post vetting notes publicly and ensure such notes are strictly in the tracker or HelpScout.

            ## Useful Resources

              - [Application Review](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/)
              - [Most Common Cases](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#most-common-cases-quick-step-by-step-guide)
              - [Video tutorials](https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#quick-step-by-step-video-tutorial-for-application-review)
      - uses: peter-evans/create-or-update-comment@v3
        if: contains(inputs.content-type, 'wordcamp')  
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            ## Next steps
              - [ ] Please assign the issue to the team member and make sure to mark the issue ```To Do```
              - [ ] Assignee (Team Member) will mark the issue as ```In Progress``` and perform the vetting taks on the tracker and HS as indicated on the handbook
              - [ ] Once the vetting is completed marke the issue as ```In Review```

            ## Public vs Private
              - Use comments for questions about the process and changes or to indicate delays, holding situation.
              - Avoid discussing the community or the organiser in comments on Github. Even if there are doubts about some applications.
              - We do not post vetting notes publicly and ensure such notes are strictly in the tracker or HelpScout.

            ## Useful Resources
              - Application Review: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/
              - Most Common Cases: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#most-common-cases-quick-step-by-step-guide
              - Video tutorial: https://make.wordpress.org/community/handbook/community-deputy/resources-and-tools/application-review/#quick-step-by-step-video-tutorial-for-application-review