# This was based on https://docs.github.com/en/actions/managing-issues-and-pull-requests/commenting-on-an-issue-when-a-label-is-added

name: Add the applicable Event Application Checklist based on a command in the issue body
on:
  issues:
    types: [opened]

jobs:
  event-checklist:
    if: ${{ contains(github.event.issue.labels.*.name, 'application') && contains(github.event.issue.labels.*.name, 'event')}}
    uses: ./.github/workflows/comment-with-checklist.yml
    with:
      content-type: "event-application"
