# https://github.com/marketplace/actions/github-script

name: Label issue when assigned
on:
  issues:
    types: [assigned]

jobs:
  label_issues:
    if: ${{ !github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - uses: actions/github-script@v6
        with:
          script: console.log(context)
      - uses: actions/github-script@v7.0.1
        if: contains(github.event.issue.labels.*.name, 'Awaiting Triage')
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: ["Awaiting Triage"]
            })
